# MirageChatParser - Module Settings Configuration

[Modules]
# Whether to start the chat parser module or not (true/false)
EnableChatParserModule = true
# Whether to start the anti-AFK module or not (true/false)
EnableAntiAFKModule = true
